spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: learningspringboot
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  # Controls the schema generation strategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Formats the generated SQL for readability
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Specifies the Hibernate dialect for PostgreSQL
